#!/bin/bash
if [ $# -ne 4 ]; then
  exit 1
fi
if [ "$1" -ne "-q" ]; then
  exit 1
fi
if [ "$2" = "1" ]; then
  python q1.py "$3" "$4"
fi
if [ "$2" = "2" ]; then
  python q2.py "$3" "$4"
fi
if [ "$2" = "3" ]; then
  python q3.py "$3" "$4"
fi
if [ "$2" = "4" ]; then
  python q4.py "$3" "$4"
fi
if [ "$2" = "5" ]; then
  python q5.py "$3" "$4"
fi
if [ "$2" = "6" ]; then
  python q6.py "$3" "$4"
fi
if [ "$2" = "7" ]; then
  python q7.py "$3" "$4"
fi
if [ "$2" = "8" ]; then
  python q8.py "$3" "$4"
fi
if [ "$2" = "9" ]; then
  python q9.py "$3" "$4"
fi